// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PagHiper.Infra;

namespace PagHiper.Infra.Migrations
{
    [DbContext(typeof(PagHiperContext))]
    partial class PagHiperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("PagHiper.Domain.Entities.Boleto", b =>
                {
                    b.Property<string>("order_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("apiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("days_due_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("discount_cents")
                        .HasColumnType("TEXT");

                    b.Property<bool>("fixed_description")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notification_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_complement")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_cpf_cnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_district")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_email")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_number")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_state")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_street")
                        .HasColumnType("TEXT");

                    b.Property<string>("payer_zip_code")
                        .HasColumnType("TEXT");

                    b.Property<string>("shipping_methods")
                        .HasColumnType("TEXT");

                    b.Property<string>("shipping_price_cents")
                        .HasColumnType("TEXT");

                    b.Property<string>("type_bank_slip")
                        .HasColumnType("TEXT");

                    b.HasKey("order_id");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Item", b =>
                {
                    b.Property<string>("item_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Boleto_OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Boletoorder_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("price_cents")
                        .HasColumnType("TEXT");

                    b.Property<string>("quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("item_id");

                    b.HasIndex("Boletoorder_id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Item", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Boleto", null)
                        .WithMany("items")
                        .HasForeignKey("Boletoorder_id");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Boleto", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
