// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PagHiper.Infra;

namespace PagHiper.Infra.Migrations
{
    [DbContext(typeof(CrudDbContext))]
    partial class PagHiperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17");

            modelBuilder.Entity("PagHiper.Domain.Entities.Boleto", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountCents")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FixedDescription")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerComplement")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerCpfCnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerDistrict")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerState")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerZipCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingMethods")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingPriceCents")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeBankSlip")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Boletos");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoletoOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceCents")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("BoletoOrderId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Item", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Boleto", null)
                        .WithMany("Items")
                        .HasForeignKey("BoletoOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
