// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PagHiper.Infra.Postgres.Context;

namespace PagHiper.Infra.Postgres.Migrations
{
    [DbContext(typeof(PostgresCrudDbContext))]
    [Migration("20220415145248_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataCadastro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelCpf")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelNome")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelParentesco")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelTelefone")
                        .HasColumnType("text");

                    b.Property<string>("Rg")
                        .HasColumnType("text");

                    b.Property<bool>("StatusCadastro")
                        .HasColumnType("boolean");

                    b.Property<bool>("StatusFinanceiro")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<string>("Contato")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("AlunoContato");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoMatricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<string>("CampanhaId")
                        .HasColumnType("text");

                    b.Property<string>("CursoId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataMatricula")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroRegistro")
                        .HasColumnType("text");

                    b.Property<string>("PagamentoId")
                        .HasColumnType("text");

                    b.Property<string>("PagamentoTipoId")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("AlunoMatricula");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoParcelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataPagamentoEfetuado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroTotalParcelas")
                        .HasColumnType("integer");

                    b.Property<string>("PagamentoEfetuado")
                        .HasColumnType("text");

                    b.Property<string>("PagamentoEfetuadoId")
                        .HasColumnType("text");

                    b.Property<string>("TipoPagamentoId")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorEfetuado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("AlunoParcelas");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoTurma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataIngresso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("AlunoTurma");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Boleto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("DaysDueDate")
                        .HasColumnType("text");

                    b.Property<string>("DiscountCents")
                        .HasColumnType("text");

                    b.Property<string>("EarlyPaymentDiscountsCents")
                        .HasColumnType("text");

                    b.Property<string>("EarlyPaymentDiscountsDays")
                        .HasColumnType("text");

                    b.Property<bool>("FixedDescription")
                        .HasColumnType("boolean");

                    b.Property<string>("LatePaymentFine")
                        .HasColumnType("text");

                    b.Property<string>("NotificationUrl")
                        .HasColumnType("text");

                    b.Property<string>("OpenAfterDayDue")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("PartnersId")
                        .HasColumnType("text");

                    b.Property<string>("PayerCity")
                        .HasColumnType("text");

                    b.Property<string>("PayerComplement")
                        .HasColumnType("text");

                    b.Property<string>("PayerCpfCnpj")
                        .HasColumnType("text");

                    b.Property<string>("PayerDistrict")
                        .HasColumnType("text");

                    b.Property<string>("PayerEmail")
                        .HasColumnType("text");

                    b.Property<string>("PayerName")
                        .HasColumnType("text");

                    b.Property<string>("PayerNumber")
                        .HasColumnType("text");

                    b.Property<string>("PayerPhone")
                        .HasColumnType("text");

                    b.Property<string>("PayerState")
                        .HasColumnType("text");

                    b.Property<string>("PayerStreet")
                        .HasColumnType("text");

                    b.Property<string>("PayerZipCode")
                        .HasColumnType("text");

                    b.Property<string>("PerDayInterest")
                        .HasColumnType("text");

                    b.Property<string>("SellerDescription")
                        .HasColumnType("text");

                    b.Property<string>("ShippingMethods")
                        .HasColumnType("text");

                    b.Property<string>("ShippingPriceCents")
                        .HasColumnType("text");

                    b.Property<string>("TypeBankSlip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Boleto");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Common.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BoletoId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<string>("PriceCents")
                        .HasColumnType("text");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoletoId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("AceitaPropaganda")
                        .HasColumnType("boolean");

                    b.Property<string>("Cupom")
                        .HasColumnType("character varying(7)")
                        .HasMaxLength(7);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("character varying(14)")
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("Lead");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoContato", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithMany("Contatos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoMatricula", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithOne("Matricula")
                        .HasForeignKey("PagHiper.Domain.Entities.Aluno.AlunoMatricula", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoParcelas", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithOne("Parcelas")
                        .HasForeignKey("PagHiper.Domain.Entities.Aluno.AlunoParcelas", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoTurma", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithMany("Turmas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PagHiper.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Common.Endereco", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithOne("Endereco")
                        .HasForeignKey("PagHiper.Domain.Entities.Common.Endereco", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Item", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Boleto", "Boleto")
                        .WithMany("Items")
                        .HasForeignKey("BoletoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
