// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PagHiper.Infra.MySql.Context;

namespace PagHiper.Infra.MySql.Migrations
{
    [DbContext(typeof(MySqlCrudDbContext))]
    partial class MySqlCrudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Boleto", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("apiKey")
                        .HasColumnType("text");

                    b.Property<string>("days_due_date")
                        .HasColumnType("text");

                    b.Property<string>("discount_cents")
                        .HasColumnType("text");

                    b.Property<string>("early_payment_discounts_cents")
                        .HasColumnType("text");

                    b.Property<string>("early_payment_discounts_days")
                        .HasColumnType("text");

                    b.Property<bool>("fixed_description")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("late_payment_fine")
                        .HasColumnType("text");

                    b.Property<string>("notification_url")
                        .HasColumnType("text");

                    b.Property<string>("open_after_day_due")
                        .HasColumnType("text");

                    b.Property<string>("order_id")
                        .HasColumnType("text");

                    b.Property<string>("partners_id")
                        .HasColumnType("text");

                    b.Property<string>("payer_city")
                        .HasColumnType("text");

                    b.Property<string>("payer_complement")
                        .HasColumnType("text");

                    b.Property<string>("payer_cpf_cnpj")
                        .HasColumnType("text");

                    b.Property<string>("payer_district")
                        .HasColumnType("text");

                    b.Property<string>("payer_email")
                        .HasColumnType("text");

                    b.Property<string>("payer_name")
                        .HasColumnType("text");

                    b.Property<string>("payer_number")
                        .HasColumnType("text");

                    b.Property<string>("payer_phone")
                        .HasColumnType("text");

                    b.Property<string>("payer_state")
                        .HasColumnType("text");

                    b.Property<string>("payer_street")
                        .HasColumnType("text");

                    b.Property<string>("payer_zip_code")
                        .HasColumnType("text");

                    b.Property<string>("per_day_interest")
                        .HasColumnType("text");

                    b.Property<string>("seller_description")
                        .HasColumnType("text");

                    b.Property<string>("shipping_methods")
                        .HasColumnType("text");

                    b.Property<string>("shipping_price_cents")
                        .HasColumnType("text");

                    b.Property<string>("type_bank_slip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Boleto");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("BoletoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("item_id")
                        .HasColumnType("text");

                    b.Property<string>("price_cents")
                        .HasColumnType("text");

                    b.Property<string>("quantity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoletoId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.Aluno", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamp");

                    b.Property<DateTimeOffset?>("DataCadastro")
                        .IsRequired()
                        .HasColumnType("timestamp");

                    b.Property<DateTimeOffset?>("DataNascimento")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelCpf")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelNome")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelParentesco")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelTelefone")
                        .HasColumnType("text");

                    b.Property<string>("Rg")
                        .HasColumnType("text");

                    b.Property<bool>("StatusCadastro")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("StatusFinanceiro")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoContato", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Contato")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("AlunoContato");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoMatricula", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("CampanhaId")
                        .HasColumnType("text");

                    b.Property<string>("CursoId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataMatricula")
                        .HasColumnType("timestamp");

                    b.Property<string>("NumeroRegistro")
                        .HasColumnType("text");

                    b.Property<string>("PagamentoId")
                        .HasColumnType("text");

                    b.Property<string>("PagamentoTipoId")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("AlunoMatricula");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoParcelas", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime?>("DataPagamentoEfetuado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("int");

                    b.Property<int>("NumeroTotalParcelas")
                        .HasColumnType("int");

                    b.Property<string>("PagamentoEfetuado")
                        .HasColumnType("text");

                    b.Property<string>("PagamentoEfetuadoId")
                        .HasColumnType("text");

                    b.Property<string>("TipoPagamentoId")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorEfetuado")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("AlunoParcelas");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoTurma", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTimeOffset>("DataIngresso")
                        .HasColumnType("timestamp");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("TurmaId")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("AlunoTurma");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Common.Endereco", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Turma", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.HasOne("Boleto", "Boleto")
                        .WithMany("items")
                        .HasForeignKey("BoletoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoContato", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithMany("Contatos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoMatricula", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithOne("Matricula")
                        .HasForeignKey("PagHiper.Domain.Entities.Aluno.AlunoMatricula", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoParcelas", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithOne("Parcelas")
                        .HasForeignKey("PagHiper.Domain.Entities.Aluno.AlunoParcelas", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Aluno.AlunoTurma", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithMany("Turmas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PagHiper.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId");
                });

            modelBuilder.Entity("PagHiper.Domain.Entities.Common.Endereco", b =>
                {
                    b.HasOne("PagHiper.Domain.Entities.Aluno.Aluno", "Aluno")
                        .WithOne("Endereco")
                        .HasForeignKey("PagHiper.Domain.Entities.Common.Endereco", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
